// Code generated by DeepSource. DO NOT EDIT.
package main

import (
        plugins "github.com/deepsourcelabs/deepsource-go/plugins"
        "log"
)

func main() {
        p := plugins.GoASTPlugin{Name: "go-ast"}
        p.RegisterRule(hello)
        p.RegisterRule(hi)
        files, err := p.BuildAST("test_dir")
        if err != nil {
                log.Fatalln(err)
        }
        err = p.Run(files)
        if err != nil {
                log.Fatalln(err)
        }
}
